tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "vitorgalvao/tiny-scripts"
# Library for manipulating PNG images
brew "libpng"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Parser generator
brew "bison"
# Software library to render fonts
brew "freetype"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Core application library for C
brew "glib"
# Linux virtual machines
brew "lima"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Small git utilities
brew "git-extras"
# OpenType text shaping engine
brew "harfbuzz"
# Improved top (interactive process viewer)
brew "htop"
# Image manipulation library
brew "jpeg"
# BSD-style licensed readline alternative
brew "libedit"
# Conversion library
brew "libiconv"
# Postgres C API library
brew "libpq"
# GNOME XML library
brew "libxml2"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Manage compile and link flags for libraries
brew "pkg-config"
# Generate C-based recognizers from regular expressions
brew "re2c"
# Cross-shell prompt for astronauts
brew "starship"
# Code-search similar to ack
brew "the_silver_searcher"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# HTTP benchmarking tool
brew "wrk"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# General-purpose lossless data-compression library
brew "zlib"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# GPU-accelerated terminal emulator
cask "alacritty"
# Reminder, planner & calendar
cask "anydo"
# Web browser focusing on privacy
cask "brave-browser"
# Voice and text chat software
cask "discord"
# App for note taking, organising, task lists, and archiving
cask "evernote"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
# File sharing, screen recording, and screenshot capture app
cask "jumpshare"
# App to write, plan, collaborate, and get organised
cask "notion"
# WebKit based web browser
cask "orion"
# Translation editor
cask "poedit"
# Collaboration platform for API development
cask "postman"
# Kubernetes and container management on the desktop
cask "rancher"
# Simple shortcut menu
cask "shuttle"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# VPN client for secure internet access and private browsing
cask "tunnelbear"
# Open-source code editor
cask "visual-studio-code"
# Network protocol analyzer
cask "wireshark"
# Word processor for handwriting
cask "write"
# Multiplayer code editor
cask "zed"
