#  ~/.zshrc

source ~/.dotfiles/zprezto/zshrc
source ~/.dotfiles/zsh/environment.zsh
source ~/.dotfiles/zsh/aliases.d/general.zsh
source ~/.dotfiles/zsh/functions.zsh

for conf (~/.dotfiles/zsh/conf.d/*(N.)) source $conf
for func (~/.dotfiles/zsh/private.d/*(N.)) autoload -U ${func:t}

osName=`uname -s | tr "[:upper:]" "[:lower:]"`
source ~/.dotfiles/zsh/aliases.d/$osName.zsh

