#  ~/.zshrc

source ~/.dotfiles/zprezto/zshrc
source ~/.dotfiles/zsh/environment.zsh
source ~/.dotfiles/zsh/aliases.d/general.zsh

for conf (~/.dotfiles/zsh/conf.d/*(N.)) source $conf
for func (~/.dotfiles/zsh/func.d/*(N.)) autoload -U ${func:t}
for func (~/.dotfiles/zsh/private.d/*(N.)) autoload -U ${func:t}

# AutoJump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
